name: "Build Beet project"
description: "Builds a beet project and provides exposed outputs to get the files"
author: "Trplnr"
branding:
  icon: 'package'
  color: 'red'

inputs:
  beet-dir:
    description: 'The directory with the beet.json'
    required: false
    default: '.'

outputs:
  data-packs:
    description: List of data packs built as a JSON array of paths
    value: ${{ steps.build-beet-project.outputs.data-packs }}

  resource-packs:
    description: List of resource packs built as a JSON array of paths
    value: ${{ steps.build-beet-project.outputs.resource-packs }}

  unknown-files:
    description: List of unknown files built as a JSON array of paths
    value: ${{ steps.build-beet-project.outputs.unknown-files }}

  beet-project-output:
    description: The output directory of the built files
    value: ${{ steps.read-beet-config.outputs.output }}

  beet-project-name:
    description: The name of the Beet project
    value: ${{ steps.read-beet-config.outputs.name }}

  beet-project-version:
    description: The version of the Beet project
    value: ${{ steps.read-beet-config.outputs.version }}


runs:
  using: composite
  steps:
    - name: "Validate project"
      id: validate-project
      shell: bash
      run: node ${{ github.action_path }}/dist/validate.js

    - name: "Install beet and dependencies"
      continue-on-error: false
      shell: bash
      run: |
        python -m pip install --upgrade pip
        REQUIREMENTS_TXT_PATH=${{ steps.validate-project.outputs.requirements-txt-path }}
        if [ -f $REQUIREMENTS_TXT_PATH ]; then pip install -r $REQUIREMENTS_TXT_PATH; fi

    - name: "Read beet config"
      id: read-beet-config
      continue-on-error: false
      shell: bash
      run: python ${{ github.action_path }}/src/read_beet_config.py
      env:
        BEET_CONFIG_PATH: ${{ steps.validate-project.outputs.beet-config-path }}

    - name: "Build Beet project"
      id: build-beet-project
      continue-on-error: false
      shell: bash
      run: node ${{ github.action_path }}/dist/build.js
      env:
        BEET_PROJECT_OUTPUT: ${{ steps.read-beet-config.outputs.output }}