name: "Test Trioplane/action-build-beet-project@v1.0.0-beta5"

on: workflow_call

jobs:
    test_action:
        runs-on: ubuntu-latest
        steps:
            - name: Build Beet project
              uses: Trioplane/action-build-beet-project@v1.0.0-beta5
              with:
                  beet-dir: 'my_beet_dir'